#!/usr/bin/env python

import argparse
import sys
import logging
import monthly

def run_program():
    parser = argparse.ArgumentParser(description='Parse dates in filenames')
    parser.add_argument('--touch', action='store_true', default=False,
                        help='change file modification date to match parsed date')
    parser.add_argument('--dir', dest='dir', required=False, default='.',
                        help='directory to run in')
    parser.add_argument('--log', dest='log', required=False, default='INFO',
                        help='logging level')

    args = parser.parse_args()
    logging.basicConfig(format='%(levelname)s: %(message)s',
                        level=getattr(logging, args.log.upper()))

    return monthly.parse_dates_in_filenames(args)

if __name__ == '__main__':
    sys.exit(run_program())
